name: Build
on:
  - push

jobs:
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          # newer version of bun is currently having issue with build
          # see https://github.com/oven-sh/bun/issues/10851
          bun-version: 1.1.4
      - run: bun install --ignore-scripts --no-progress
      - run: bun build/index.ts
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-artifacts
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ vars.DOCKER_IMAGE }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.github
          push: true
          tags: ${{ steps.meta.outputs.tags }}
