name: Build Image
on:
  - push
  - workflow_dispatch

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - run: bun install --ignore-scripts --no-progress
      - run: bun build/index.ts
      - id: meta
        run: bun build/generate-tags.ts ${{ vars.DOCKER_IMAGE }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.github
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.url="${{ github.repositoryUrl }}"
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUN_VERSION=${{ steps.setup-bun.outputs.bun-version }}
